# Generated by Django 4.0 on 2022-01-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelWine',
            fields=[
                ('보유와인번호', models.AutoField(primary_key=True, serialize=False)),
                ('와인번호', models.IntegerField(default=0)),
                ('군집', models.IntegerField(default=0)),
                ('평점', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'db_table': 'HotelWine',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('주문', models.AutoField(primary_key=True, serialize=False)),
                ('룸넘버', models.IntegerField(default=0)),
                ('보유와인번호', models.ForeignKey(db_column='보유와인번호', on_delete=django.db.models.deletion.CASCADE, to='api.hotelwine')),
            ],
        ),
    ]
